version: '3'
services:
  node-express-app:
    build:
      context: .
    ports:
      - "4000:3333"

  mongo-service:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=peleg
      - MONGO_INITDB_ROOT_PASSWORD=1234
